FROM tomsmithokta/awscli-python279

#RUN apt-get update && apt-get install -y \
#	python-pip \
#	virtualenv \
#	git \
# && rm -rf /var/lib/apt/lists/*

RUN pip install awsprocesscreds

# RUN pip install virtualenv

# RUN apt-get update && apt-get install -y \
#	git \
# && rm -rf /var/lib/apt/lists/*

#RUN git clone https://github.com/awslabs/awsprocesscreds.git