FROM tomsmithokta/python:2.7.9

RUN apt-get update && apt-get install -y awscli

# RUN pip install awscli --upgrade --user

# RUN apt-get update && apt-get install -y \
#	curl \
#	unzip \
# && rm -rf /var/lib/apt/lists/*

# RUN curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"

# RUN unzip awscli-bundle.zip

# RUN ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

# RUN echo "export PATH=~/.local/bin:$PATH" >> /root/.profile